FORMAT: 1A

# CIG-Exchange p2p API
This is a **API Blueprint** file that describes **CIG-Exchange p2p API**.


# Group Ping

## p2p/api/ping [/p2p/api/ping]

### Ping test [GET]
Execute an api ping test.
+ Response 200 (application/json)
    + Attributes (Ping Response)


# Group Offerings

## p2p/api/offerings [/p2p/api/offerings]

### Create offering [POST]
Creates a new Offering object.
Offering 'id' is ignored in request and will be assigned in response.

+ Request (application/json)
    + Attributes (Offering Request)

+ Response 200 (application/json)
    + Attributes (Offering Response)

### Retrieve all offerings [GET]
Returns all Offerings available on the server.

+ Response 200 (application/json)
    + Attributes (array[Offering Response])

## p2p/api/offerings/{offering_id} [/p2p/api/offerings/{offering_id}]

### Retrieve offering [GET]
Returns a specific Offering object.

+ Parameters
    + offering_id: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - UUID of the offering

+ Response 200 (application/json)
    + Attributes (Offering Response)

### Update offering [PATCH]
Updates a specific Offering object.
Fields that are present in json will be updated, even when they are empty.

+ Parameters
    + offering_id: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - UUID of the offering

+ Request (application/json)
    + Attributes (Offering Request)

+ Response 200 (application/json)
    + Attributes (Offering Response)

### Delete offering [DELETE]
Deletes a specific Offering object.

+ Parameters
    + offering_id: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - UUID of the offering

+ Response 204


## Data Structures

### Ping Response
+ message: Pong! (string, required) - ping response message
+ status: true (boolean, required) - ping response status


### Offering Request
+ title: title (string) - offering title
+ type: type1, type2 (array[string]) - offering types array
+ description: description (string) - offering description
+ rating: rating (string) - offering rating
+ amount: 200.98 (number) - offering amount
+ remaining: 100.66 (number) - offering remaining
+ interest: 10.5 (number) - offering interest
+ period: 300 (number) - offering period
+ origin: origin (string) - offering origin
+ organisation_id: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - offering organisation

### Offering Response
+ id: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - offering UUID
+ title: title (string, required) - offering title
+ type: type1, type2 (array[string], required) - offering types array
+ description: description (string, required) - offering description
+ rating: rating (string, required) - offering rating
+ amount: 200.98 (number, required) - offering amount
+ remaining: 100.66 (number, required) - offering remaining
+ interest: 10.5 (number, required) - offering interest
+ period: 300 (number, required) - offering period
+ origin: origin (string, required) - offering origin
+ organisation_id: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - offering organisation
+ created_at: `2018-12-20T12:18:32+00:00` (string, required) - offering creation timestamp
+ updated_at: `2018-12-20T12:18:32+00:00` (string, required) - offering updated timestamp
