FORMAT: 1A

# CIG-Exchange API
This is a **API Blueprint** file that describes **CIG-Exchange API**.


# Group Trading/Ping

## invest/api/ping [/invest/api/ping]

### Ping test [GET]
Execute an api ping test.
+ Response 200 (application/json)
    + Attributes (Ping Response)


# Group Trading/Contact Us

## invest/api/contact_us [/invest/api/contact_us]

### Contact Us [POST]
Send contact us email message.

+ Request (application/json)
    + Attributes (ContactUs Request)

+ Response 204


# Group Trading/Offerings

## invest/api/offerings [/invest/api/offerings]

### Offerings [GET]
Get visible offerings from verified organisations.
This call doesn't require JWT.

+ Response 200 (application/json)
    + Attributes (array[Trading Offering Response])


# Group Trading/Users

## invest/api/users/activities [/invest/api/users/activities]

### Create activity [POST]
Create a new UserActivity object.
Api call will save request body as jsonb in 'user_activity.info' field.

+ Request (application/json)
    + Attributes (Activity Request)

+ Response 204

## invest/api/users/signup [/invest/api/users/signup]

### Signup [POST]
Create a new account.

+ Request (application/json)
    + Attributes (User Request)

+ Response 200 (application/json)
    + Attributes (User Response)

## invest/api/users/signin [/invest/api/users/signin]

### Signin [POST]
Login to existing account.
Either email or mobile should be specified.

+ Request (application/json)
    + Attributes (User Signin Request)

+ Response 200 (application/json)
    + Attributes (User Response)

## invest/api/users/send_otp [/invest/api/users/send_otp]

### Send OTP [POST]
Send one time password.
Supported types are "email" and "phone"

+ Request (application/json)
    + Attributes (OTP Send Request)

+ Response 204

## invest/api/users/verify_otp [/invest/api/users/verify_otp]

### Verify OTP [POST]
Verify one time password.
Supported types are "email" and "phone".
On success, jwt is returned.

+ Request (application/json)
    + Attributes (OTP Verify Request)

+ Response 200 (application/json)
    + Attributes (OTP Response)


# Group Trading/Organisations

## invest/api/organisations/signup [/invest/api/organisations/signup]

### Create organisation [POST]
Creates a new Organisation object and User object.
User will be admin in created organisation.
On success, user id is returned.

+ Request (application/json)
    + Attributes (Create Organisation Request)

+ Response 200 (application/json)
    + Attributes (User Response)


# Group P2P/Me

## p2p/api/me/info [/p2p/api/me/info]

### Get user info [GET]
Returns user info.

+ Response 200 (application/json)
    + Attributes (Info Response)

# Group P2P/JWT

## p2p/api/ping-jwt [/p2p/api/ping-jwt]

### Ping JWT [GET]
Checks user jwt.
For outdated jwt api call will return status code 401.

+ Response 204

# Group P2P/Users

## p2p/api/users/switch/{organisation} [/p2p/api/users/switch/{organisation}]

### Switch Organisation [POST]
Changes organisation.
On success, jwt is returned.

+ Parameters
    + organisation: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - organisation id

+ Response 200 (application/json)
    + Attributes (OTP Response)

## p2p/api/users/{user} [/p2p/api/users/{user}]

### Retrieve user [GET]
Returns a specific User object.

+ Parameters
    + user: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - user id

+ Response 200 (application/json)
    + Attributes (Update User Response)

### Update user [PATCH]
Updates a specific User object.
Fields that are present in json will be updated, even when they are empty.

+ Parameters
    + user: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - user id

+ Request (application/json)
    + Attributes (Update User Request)

+ Response 200 (application/json)
    + Attributes (Update User Response)

## p2p/api/users/{user}/activities [/p2p/api/users/{user}/activities]

### Retrieve user activities [GET]
Returns all UserActivities for user.

+ Parameters
    + user: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - user id

+ Response 200 (application/json)
    + Attributes (array[Activity Response])

### Create user activity [POST]
Create a new UserActivity object.
Api call will save request body as jsonb in 'user_activity.info' field.
JWT will be saved as jsonb in 'user_activity.jwt' field.

+ Parameters
    + user: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - user id

+ Request (application/json)
    + Attributes (Activity Request)

+ Response 204


# Group P2P/Offerings

## p2p/api/organisations/{organisation}/offerings [/p2p/api/organisations/{organisation}/offerings]

### Create offering [POST]
Creates a new Offering object.
Offering 'id' is ignored in request and will be assigned in response.

+ Parameters
    + organisation: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - organisation id

+ Request (application/json)
    + Attributes (Offering Request)

+ Response 200 (application/json)
    + Attributes (Offering Response)

### Retrieve all offerings [GET]
Returns all Offerings available on the server.

+ Parameters
    + organisation: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - organisation id

+ Response 200 (application/json)
    + Attributes (array[Offering Response])

## p2p/api/organisations/{organisation}/offerings/{offering} [/p2p/api/organisations/{organisation}/offerings/{offering}]

### Retrieve offering [GET]
Returns a specific Offering object.

+ Parameters
    + organisation: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - organisation id
    + offering: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - UUID of the offering

+ Response 200 (application/json)
    + Attributes (Offering Response)

### Update offering [PATCH]
Updates a specific Offering object.
Fields that are present in json will be updated, even when they are empty.

+ Parameters
    + organisation: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - organisation id
    + offering: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - UUID of the offering

+ Request (application/json)
    + Attributes (Offering Update Request)

+ Response 200 (application/json)
    + Attributes (Offering Response)

### Delete offering [DELETE]
Deletes a specific Offering object.

+ Parameters
    + organisation: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - organisation id
    + offering: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - UUID of the offering

+ Response 204


# Group P2P/Invitations

## p2p/api/organisations/{organisation}/invitations [/p2p/api/organisations/{organisation}/invitations]

### Send invitation [POST]
Creates user if not exist or invites existing user to organisation.
Returns invited user id on success.

+ Parameters
    + organisation: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - organisation id

+ Request (application/json)
    + Attributes (Invitation Request)

+ Response 200 (application/json)
    + Attributes (User Response)

### Retrieve invitations [GET]
Returns all Invitations for organisation.

+ Parameters
    + organisation: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - organisation id

+ Response 200 (application/json)
    + Attributes (array[OrganisationUser Response])

## p2p/api/organisations/{organisation}/invitations/{user} [/p2p/api/organisations/{organisation}/invitations/{user}]

### Delete invitation [DELETE]
Deletes a specific invitation.

+ Parameters
    + organisation: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - organisation id
    + user: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - UUID of the user to cancel invitation

+ Response 204


# Group P2P/OrganisationUsers

## p2p/api/organisations/{organisation}/users [/p2p/api/organisations/{organisation}/users]

### Retrieve organisation users [GET]
Returns all users belonging to sepcified organisation.

+ Parameters
    + organisation: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - organisation id

+ Response 200 (application/json)
    + Attributes (array[OrganisationUser Response])

## p2p/api/organisations/{organisation}/users/{user} [/p2p/api/organisations/{organisation}/users/{user}]

### Delete organisation user [DELETE]
Deletes a specific organisation user.
Only admin and organisation admin can use this api call.
Organisation admin can't delete himself from organisation.

+ Parameters
    + organisation: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - organisation id
    + user: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - UUID of the user to delete from the organisation

+ Response 204

### Add organisation user [POST]
Only admin can directly add user to organisation.
Other users must use /p2p/api/organisations/{organisation}/invitations.

+ Parameters
    + organisation: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - organisation id
    + user: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - UUID of the user to add from the organisation

+ Response 204

# Group P2P/Organisations

## p2p/api/organisations [/p2p/api/organisations]

### Create organisation [POST]
Creates a new Organisation object.
Organisation 'id' is ignored in request and will be assigned in response.

+ Request (application/json)
    + Attributes (Organisation Request)

+ Response 200 (application/json)
    + Attributes (Organisation Response)

### Retrieve all organisations [GET]
Returns all Organisations for user.

+ Response 200 (application/json)
    + Attributes (array[Organisation Response])

## p2p/api/organisations/{organisation} [/p2p/api/organisations/{organisation}]

### Retrieve organisation [GET]
Returns a specific Organisation object.
Admin can retrieve any organisation.

+ Parameters
    + organisation: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - organisation id

+ Response 200 (application/json)
    + Attributes (Organisation Response)

### Update organisation [PATCH]
Updates a specific Organisation object.
Fields that are present in json will be updated, even when they are empty.

+ Parameters
    + organisation: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - organisation id

+ Request (application/json)
    + Attributes (Organisation Request)

+ Response 200 (application/json)
    + Attributes (Organisation Response)

### Delete organisation [DELETE]
Deletes a specific Organisation object.
Only admin user can delete organisation.

+ Parameters
    + organisation: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - organisation id

+ Response 204


## Data Structures

### Ping Response
+ `message`: `Pong!` (string, required) - ping response message
+ `status`: `true` (boolean, required) - ping response status

### Activity Request
+ `type`: `type` (string, required) - activity type
+ `any_field`: `any_field` (string) - any addition data

### Activity Response
+ `id`: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - user activity UUID
+ `user_id`: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - user UUID
+ `type`: `type` (string, required) - activity type
+ `info` (object, required) - activity info
+ `jwt` (object, required) - activity jwt
+ `created_at`: `2018-12-20T12:18:32+00:00` (string, required) - user activity creation timestamp
+ `updated_at`: `2018-12-20T12:18:32+00:00` (string, required) - user activity updated timestamp

### ContactUs Request
+ `name`: `Dredd Test` (string, required) - name
+ `email`: `email` (string, required) - email
+ `message`: `This is a dredd test generated email` (string, required) - message

### Map Object
+ `any_field`: `any_value` (string) - map values

### Trading Offering Response
+ `id`: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - offering UUID
+ `title`: `title` (string, required) - offering title
+ `title_map` (Multilanguage String, required) - offering title map
+ `type`: `type1, type2` (array[string], required) - offering types array
+ `description`: `description` (string, required) - offering description
+ `description_map` (Multilanguage String, required) - offering description map
+ `rating`: `rating` (string, required) - offering rating
+ `rating_map` (Multilanguage String, required) - offering rating map
+ `slug`: `slug` (string, required) - offering slug
+ `slug_map` (Multilanguage String, required) - offering slug map
+ `amount`: `200.98` (number, required) - offering amount
+ `remaining`: `100.66` (number, required) - offering remaining
+ `interest`: `10.5` (number, required) - offering interest
+ `period`: `300` (number, required) - offering period
+ `origin`: `origin` (string, required) - offering origin
+ `origin_map` (Multilanguage String, required) - offering origin map
+ `map` (Map Object, required) - offering map object
+ `location`: `location` (string, required) - offering location
+ `location_map` (Multilanguage String, required) - offering location map
+ `tagline1`: `tagline1` (string, required) - offering tagline 1
+ `tagline1_map` (Multilanguage String, required) - offering tagline1 map
+ `tagline2`: `tagline2` (string, required) - offering tagline 2
+ `tagline2_map` (Multilanguage String, required) - offering tagline2 map
+ `tagline3`: `tagline3` (string, required) - offering tagline 3
+ `tagline3_map` (Multilanguage String, required) - offering tagline3 map
+ `current_debt_level`: `current_debt_level` (string, required) - current debt level
+ `current_debt_level_map` (Multilanguage String, required) - current debt level map
+ `current_debt_end_datetime`: `2016-06-23` (string, required) - current debt end datetime
+ `amount_already_taken`: `300` (number, required) - amount already taken
+ `minimum_investment`: `10` (number, required) - offering minimum_investment
+ `maximum_investment`: `500` (number, required) - offering maximum_investment
+ `transaction_fee`: `100` (number, required) - offering transaction fee
+ `p2p_fee`: `20` (number, required) - offering p2p fee
+ `referral_reward`: `20` (number, required) - offering referral reward
+ `closing_date`: `2016-06-23` (string, required) - offering closing date
+ `is_visible`: `true` (boolean, required) - offering visibility flag
+ `offering_direct_url` (Offering Direct Urls, required) - offering direct url
+ `organisation`: `organisation` (string, required) - offering organisation name
+ `organisation_website`: `website` (string, required) - offering website
+ `organisation_id`: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - offering organisation
+ `created_at`: `2018-12-20T12:18:32+00:00` (string, required) - offering creation timestamp
+ `updated_at`: `2018-12-20T12:18:32+00:00` (string, required) - offering updated timestamp

### Offering Request
+ `title` (Multilanguage String, required) - offering title
+ `type`: `type1, type2` (array[string], required) - offering types array
+ `description` (Multilanguage String) - offering description
+ `rating` (Multilanguage String) - offering rating
+ `slug` (Multilanguage String) - offering slug
+ `amount`: `200.98` (number) - offering amount
+ `remaining`: `100.66` (number) - offering remaining
+ `interest`: `10.5` (number) - offering interest
+ `period`: `300` (number) - offering period
+ `origin`: `origin` (string, required) - offering origin
+ `map` (Map Object) - offering map object
+ `location` (Multilanguage String) - offering location object
+ `tagline1` (Multilanguage String) - offering tagline 1
+ `tagline2` (Multilanguage String) - offering tagline 2
+ `tagline3` (Multilanguage String) - offering tagline 3
+ `current_debt_level` (Multilanguage String) - current debt level
+ `current_debt_end_datetime`: `2016-06-23` (string) - current debt end datetime
+ `amount_already_taken`: `300` (number) - amount already taken
+ `minimum_investment`: `10` (number) - offering minimum_investment
+ `maximum_investment`: `500` (number) - offering maximum_investment
+ `transaction_fee`: `100` (number) - offering transaction fee
+ `p2p_fee`: `20` (number) - offering p2p fee
+ `referral_reward`: `20` (number) - offering referral reward
+ `closing_date`: `2016-06-23` (string) - offering closing date
+ `is_visible`: `true` (boolean) - offering visibility flag
+ `offering_direct_url` (Offering Direct Urls, required) - offering direct url
+ `organisation_id`: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - offering organisation

### Offering Update Request
+ `title` (Multilanguage String) - offering title
+ `type`: `type1, type2` (array[string]) - offering types array
+ `description` (Multilanguage String) - offering description
+ `rating` (Multilanguage String) - offering rating
+ `slug` (Multilanguage String) - offering slug
+ `amount`: `200.98` (number) - offering amount
+ `remaining`: `100.66` (number) - offering remaining
+ `interest`: `10.5` (number) - offering interest
+ `period`: `300` (number) - offering period
+ `origin`: `origin` (string) - offering origin
+ `map` (Map Object) - offering map object
+ `location` (Multilanguage String) - offering location object
+ `tagline1` (Multilanguage String) - offering tagline 1
+ `tagline2` (Multilanguage String) - offering tagline 2
+ `tagline3` (Multilanguage String) - offering tagline 3
+ `current_debt_level` (Multilanguage String) - current debt level
+ `current_debt_end_datetime`: `2016-06-23` (string) - current debt end datetime
+ `amount_already_taken`: `300` (number) - amount already taken
+ `minimum_investment`: `10` (number) - offering minimum_investment
+ `maximum_investment`: `500` (number) - offering maximum_investment
+ `transaction_fee`: `100` (number) - offering transaction fee
+ `p2p_fee`: `20` (number) - offering p2p fee
+ `referral_reward`: `20` (number) - offering referral reward
+ `closing_date`: `2016-06-23` (string) - offering closing date
+ `is_visible`: `true` (boolean) - offering visibility flag
+ `offering_direct_url` (Offering Direct Urls) - offering direct url
+ `organisation_id`: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string) - offering organisation

### Multilanguage String
+ `en`: `string` (string) - en
+ `fr`: `string` (string) - fr
+ `it`: `string` (string) - it
+ `de`: `string` (string) - de

### Offering Direct Urls
+ `en`: `url` (string, required) - offering direct url(en)
+ `fr`: `url` (string, required) - offering direct url(fr)
+ `it`: `url` (string, required) - offering direct url(it)
+ `de`: `url` (string, required) - offering direct url(de)

### Offering Response
+ `id`: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - offering UUID
+ `title`: `title` (string, required) - offering title
+ `title_map` (Multilanguage String, required) - offering title map
+ `type`: `type1, type2` (array[string], required) - offering types array
+ `description`: `description` (string, required) - offering description
+ `description_map` (Multilanguage String, required) - offering description map
+ `rating`: `rating` (string, required) - offering rating
+ `rating_map` (Multilanguage String, required) - offering rating map
+ `slug`: `slug` (string, required) - offering slug
+ `slug_map` (Multilanguage String, required) - offering slug map
+ `amount`: `200.98` (number, required) - offering amount
+ `remaining`: `100.66` (number, required) - offering remaining
+ `interest`: `10.5` (number, required) - offering interest
+ `period`: `300` (number, required) - offering period
+ `origin`: `origin` (string, required) - offering origin
+ `origin_map` (Multilanguage String, required) - offering origin map
+ `map` (Map Object, required) - offering map object
+ `location`: `location` (string, required) - offering location
+ `location_map` (Multilanguage String, required) - offering location map
+ `tagline1`: `tagline1` (string, required) - offering tagline 1
+ `tagline1_map` (Multilanguage String, required) - offering tagline1 map
+ `tagline2`: `tagline2` (string, required) - offering tagline 2
+ `tagline2_map` (Multilanguage String, required) - offering tagline2 map
+ `tagline3`: `tagline3` (string, required) - offering tagline 3
+ `tagline3_map` (Multilanguage String, required) - offering tagline3 map
+ `current_debt_level`: `current_debt_level` (string, required) - current debt level
+ `current_debt_level_map` (Multilanguage String, required) - current debt level map
+ `current_debt_end_datetime`: `2016-06-23` (string, required) - current debt end datetime
+ `amount_already_taken`: `300` (number, required) - amount already taken
+ `minimum_investment`: `10` (number, required) - offering minimum_investment
+ `maximum_investment`: `500` (number, required) - offering maximum_investment
+ `transaction_fee`: `100` (number, required) - offering transaction fee
+ `p2p_fee`: `20` (number, required) - offering p2p fee
+ `referral_reward`: `20` (number, required) - offering referral reward
+ `closing_date`: `2016-06-23` (string, required) - offering closing date
+ `is_visible`: `true` (boolean, required) - offering visibility flag
+ `offering_direct_url` (Offering Direct Urls, required) - offering direct url
+ `organisation_id`: `38e47f7e-1ecc-11e9-ab14-d663bd873d94` (string, required) - offering organisation
+ `created_at`: `2018-12-20T12:18:32+00:00` (string, required) - offering creation timestamp
+ `updated_at`: `2018-12-20T12:18:32+00:00` (string, required) - offering updated timestamp

### Update User Request
+ `name`: `Updated First Name` (string) - user first name
+ `lastname`: `Updated Last Name` (string) - user last name
+ `sex`: `female` (string) - user sex

### Update User Response
+ `id`: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - user UUID
+ `name`: `Updated First Name` (string, required) - user first name
+ `lastname`: `Updated Last Name` (string, required) - user last name
+ `sex`: `female` (string, required) - user sex

### Invitation Request
+ `name`: `First Name` (string, required) - user first name
+ `lastname`: `Last Name` (string, required) - user last name
+ `sex`: `male` (string, required) - user sex
+ `email`: `dev+test+org@cig-exchange.ch` (string, required) - user email
+ `phone_country_code`: `+1` (string, required) - user mobile number code
+ `phone_number`: `1111111111` (string, required) - user mobile number

### Create Organisation Request
+ `name`: `First Name` (string, required) - user first name
+ `lastname`: `Last Name` (string, required) - user last name
+ `sex`: `male` (string, required) - user sex
+ `email`: `dev+test+org@cig-exchange.ch` (string, required) - user email
+ `phone_country_code`: `+1` (string, required) - user mobile number code
+ `phone_number`: `1111111111` (string, required) - user mobile number
+ `organisation_name`: `organisation_name` (string) - organisation name
+ `reference_key`: `reference_key` (string) - organisation reference key

### Organisation Request
+ `type`: `type` (string) - organisation type
+ `name`: `name` (string) - organisation name
+ `website`: `website` (string) - organisation website
+ `reference_key`: `reference_key` (string) - organisation reference key
+ `offering_rating_description`: `offering_rating_description` (string) - organisation offering rating description
+ `status`: `unverified` (string) - organisation status

### Organisation Response
+ `id`: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - organisation UUID
+ `type`: `type` (string) - organisation type
+ `name`: `name` (string) - organisation name
+ `website`: `website` (string) - organisation website
+ `reference_key`: `reference_key` (string) - organisation reference key
+ `offering_rating_description`: `offering_rating_description` (string) - organisation offering rating description
+ `status`: `unverified` (string) - organisation status
+ `created_at`: `2018-12-20T12:18:32+00:00` (string, required) - organisation creation timestamp
+ `updated_at`: `2018-12-20T12:18:32+00:00` (string, required) - organisation updated timestamp

### User Request
+ `name`: `First Name` (string, required) - user first name
+ `lastname`: `Last Name` (string, required) - user last name
+ `sex`: `male` (string, required) - user sex
+ `email`: `dev+test@cig-exchange.ch` (string, required) - user email
+ `phone_country_code`: `+1` (string, required) - user mobile number code
+ `phone_number`: `1111111111` (string, required) - user mobile number
+ `reference_key`: `credit_24_gate` (string) - organisation reference key, required for 'p2p' platform
+ `platform`: `trading` (string, required) - platform to create account on, supported values are 'p2p' and 'trading'

### User Signin Request
+ `email`: `dev+test@cig-exchange.ch` (string) - user email
+ `phone_country_code`: `+1` (string) - user mobile number code
+ `phone_number`: `1111111111` (string) - user mobile number

### User Response
+ `uuid`: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - user account uuid

### OTP Send Request
+ `uuid`: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - user account uuid
+ `type`: `email` (string, required) - otp type, supported values are 'email' and 'phone'

### OTP Verify Request
+ `uuid`: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - user account uuid
+ `type`: `email` (string, required) - otp type, supported values are 'email' and 'phone'
+ `code`: `123456` (string, required) - otp code

### OTP Response
+ `jwt`: `1234567890` (string, required) - jwt for futher auth

### Info Response
+ `user_id`: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - user account uuid
+ `role`: `admin` (string, required) - user role
+ `organisation_id`: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - organisation uuid
+ `organisation_role`: `admin` (string, required) - organisation role
+ `email`: `dev+test@cig-exchange.ch` (string, required) - user email

### OrganisationUser Response
+ `id`: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - user account uuid
+ `name`: `First Name` (string, required) - user first name
+ `last_name`: `Last Name` (string, required) - user last name
+ `sex`: `male` (string, required) - user sex
